export const students = [
    { 
        id: 1,
        name: "Nitesh Kumar",
        ticketNo:"T01",
        ticketTopic:"FrontEnd",
        examGrade:5,
        ratingGrade:4,
        comments:"Nitesh is a good boy with great academic performance and good morality. Although he can do better."
    },
    {
        id: 2,
        name: "Abhishek",
        ticketNo: "T57",
        ticketTopic: "TDSA",
        examGrade: "10",
        ratingGrade: "7",
        comments: "Good at DSA",
      },
      {
        id: 3,
        name: "Vivek",
        ticketNo: "T118",
        ticketTopic: "Tjavascript",
        examGrade: "10",
        ratingGrade: "1",
        comments: "poor performance in javascript",
      },
      {
        id: 4,
        name: "Shaksham",
        ticketNo: "157",
        ticketTopic: "TCSS",
        examGrade: "6",
        ratingGrade: "8",
        comments: "Good in javascript",
      },
      {
        id: 5,
        name: "Anuj",
        ticketNo: "T257",
        ticketTopic: "T1Angular",
        examGrade: "7",
        ratingGrade: "2",
        comments: "Need to work on Angular",
      },
      {
        id: 6,
        name: "Aditi Singh",
        ticketNo: "T123",
        ticketTopic: "Epam",
        examGrade: 9,
        ratingGrade: 8,
        comments: "Aditi is a diligent student and shows a good grasp of html concepts.",

      },
      {
        id: 7,
        name: "Alok Kumar",
        ticketNo: "T456",
        ticketTopic: "F1React",
        examGrade: 8,
        ratingGrade: 9,
        comments: "Alok has a natural talent for react and shows great potential for further study.",
      },
      {id: 8,
        name: "Anjali Desai",
        
        ticketNo: "T789",
        ticketTopic: "G1Webpack",
        examGrade: 4,
        ratingGrade: 8,
        comments: "Anjali struggled with some of the Webpack concepts",
      },
      {
        name: "Arjun Reddy",
        id: 9,
        ticketNo: "T111",
        ticketTopic: "Epam",
        examGrade: 9,
        ratingGrade: 10,
        comments: "Arjun has a keen interest in Front-end and shows a strong aptitude for the subject.",
      
      },
      {
        name: "Ayesha Gupta",
        id: 10,
        ticketNo: "T222",
        ticketTopic: "Epam",
        examGrade: 8,
        ratingGrade: 9,
        comments: "Ayesha is a skilled programmer and has a strong understanding of computer science principles.",
      },
      {
        name: "Chandan Patel",
        id: 11,
        ticketNo: "T333",
        ticketTopic: "TDSA",
        examGrade: 6,
        ratingGrade: 7,
        comments: "Chandan needs to work on developing a deeper understanding of historical events and their significance.",
      },
      {
        name: "Divya Sharma",
        id: 12,
        ticketNo: "T555",
        ticketTopic: "T1Angular",
        examGrade: 2,
        ratingGrade: "4",
        comments: "Divya needs to work on understanding some of the more complex angular concepts.",
        
      },
      {
        name: "Gaurav Singh",
        id: 13,
        ticketNo: "T666",
        ticketTopic: "TReact",
        examGrade: 10,
        ratingGrade: 9,
        comments: "Gaurav is a talented in react and has shown excellent problem-solving skills.",
        "address": "666 Maple St, Lucknow, Uttar Pradesh",
        "email": "gaurav.singh@email.com",
        "contact": "7903153940"
      },
      {
        name: "Ishita Patel",
        id: 14,
        ticketNo: "T777",
        ticketTopic: "TDSA",
        examGrade: 8,
        ratingGrade: 9,
        comments: "Ishita has a strong understanding of DSA and shows great potential for further study.",
        "address": "777 Elm St, Surat, Gujarat",
        "email": "ishita.patel@email.com",
        "contact": "3680764528"
      },
      {
        name: "Jatin Mehta",
        id: 15,
        ticketNo: "T888",
        ticketTopic: "Epam",
        examGrade: 9,
        ratingGrade: 10,
        comments: "Jatin has a deep interest in Epam training",
        "address": "888 Cherry St, Ludhiana, Punjab",
        "email": "jatin.mehta@email.com",
        "contact": "4280964548"
      },
      {
        name: "Kavya Verma",
        id: 16,
        ticketNo: "T999",
        ticketTopic: "Computer Science",
        examGrade: 8,
        ratingGrade: 9,
        comments: "Kavya is a skilled programmer and has a strong understanding of computer science principles.",
        "address": "999 Oak St, Bhopal, Madhya Pradesh",
        "email": "kavya.verma@email.com",
        "contact": "7880944528"
      },
      {
        name: "Manisha Mishra",
        id: 17,
        ticketNo: "T100",
        ticketTopic: "Tpromises",
        examGrade: 7,
        ratingGrade: 6,
        comments: "Manisha needs to work on developing a deeper understanding of promises",
        "address": "100 Maple St, Varanasi, Uttar Pradesh",
        "email": "manisha.mishra@email.com",
        "contact": "6375964528"
      },
      {
        name: "Rahul Gupta",
        id: 18,
        ticketNo: "T300",
        ticketTopic: "TCSS",
        examGrade: 4,
        ratingGrade: 2,
        comments: "Rahul has to work on css",
        "address": "300 Oak St, Mumbai, Maharashtra",
        "email": "rahul.gupta@email.com",
        "contact": "8280694528"
      },
      {
        name: "Siddhi Singhania",
        id: 19,
        ticketNo: "T400",
        ticketTopic: "Tjavascript",
        examGrade: 3,
        ratingGrade: 4,
        comments: "Need to work on javascript",
        "address": "400 Maple St, Kolkata, West Bengal",
        "email": "siddhi.singhania@email.com",
        "contact": "7180964525"
      }
]